ALTER TABLE users ADD COLUMN robotLevel3x3 INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN robotLevel15x15 INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE users DROP COLUMN rating;


UPDATE users SET robotLevel3x3 = 500;
UPDATE users SET robotLevel15x15 = 500;