ALTER TABLE rating DROP COLUMN score;
ALTER TABLE rating ADD COLUMN score15x15vsPerson INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE rating ADD COLUMN score3x3vsPerson INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE rating ADD COLUMN score15x15vsRobot INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE rating ADD COLUMN score3x3vsRobot INT(11) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE rating DROP COLUMN updated;
ALTER TABLE rating DROP COLUMN position;
ALTER TABLE rating ADD COLUMN position INT(11) UNSIGNED NOT NULL DEFAULT 0;