/**
 * Id-ишники профайлера.
 * и таймер профайлера.
 */
/* SAPIUser  1 */
Profiler.ID_AUTH_VK = Profiler.getNewId("ID_AUTH_VK");
/* 2 */
Profiler.ID_SEND_USER_INFO = Profiler.getNewId("ID_SEND_USER_INFO");
/* 3 */
Profiler.ID_UPDATE_SOCNET_INFO = Profiler.getNewId("ID_UPDATE_SOCNET_INFO");
/* 4 */
Profiler.ID_SEND_FRIENDS = Profiler.getNewId("ID_SEND_FRIENDS");
/* 5 */
Profiler.ID_SENDME_ONLINE = Profiler.getNewId("ID_SENDME_ONLINE");
/* SAPIChat */
/* 6 */
Profiler.ID_GET_LAST_MESSAGES = Profiler.getNewId("ID_GET_LAST_MESSAGES");
/* 7 */
Profiler.ID_CHAT_SEND_MESSAGE = Profiler.getNewId("ID_CHAT_SEND_MESSAGE");
/* SAPIUserState */
/* 8 */
Profiler.ID_USER_IS_BUSY = Profiler.getNewId("ID_USER_IS_BUSY");
/* 9 */
Profiler.ID_USER_IS_NO_BUSY = Profiler.getNewId("ID_USER_IS_NO_BUSY");
/* 10 */
Profiler.ID_USER_ON_GAME = Profiler.getNewId("ID_USER_ON_GAME");
/* SAPIInvites */
/* 11 */
Profiler.ID_SEND_INVITE = Profiler.getNewId("ID_SEND_INVITE");
/* LogicUser */
/* 12 */
Profiler.ID_LOGIC_SEND_TO_ALL = Profiler.getNewId("ID_LOGIC_SEND_TO_ALL");
/* WebSocketServer */
/* 13 */
Profiler.ID_WEBSOCKETSERVER_SEND_IMAGE = Profiler.getNewId("ID_WEBSOCKETSERVER_SEND_IMAGE"); // unused, but id nedded //
/* 14 */
Profiler.ID_WEBSOCKETSERVER_SEND_CLIENT_CODE = Profiler.getNewId("ID_WEBSOCKETSERVER_SEND_CLIENT_CODE");
/* SAPIRating*/
/* 15 */
Profiler.ID_SAPIRATING_SEND_ME_TOP_LIST = Profiler.getNewId("ID_SAPIRATING_SEND_ME_TOP_LIST");
/* SAPIGame */
/* 16 */
Profiler.ID_SAPIGAME_REQUEST_RANDOM_GAME = Profiler.getNewId("ID_SAPIGAME_REQUEST_RANDOM_GAME");
/* 17 */
Profiler.ID_SAPIGAME_CANCEL_RANDOM_GAME = Profiler.getNewId("ID_SAPIGAME_CANCEL_RANDOM_GAME");
/* 18 */
Profiler.ID_DO_MOVE = Profiler.getNewId("ID_DO_MOVE");
/* ActionsGame */
/* 19 */
Profiler.ID_CREATE_WAITER = Profiler.getNewId("ID_CREATE_WAITER");
/* 20 */
Profiler.ID_CREATE_RANDOM_GAME = Profiler.getNewId("ID_CREATE_RANDOM_GAME");
/* SAPIRobot */
/* 21 */
Profiler.ID_CREATE_ROBOT_GAME = Profiler.getNewId("ID_CREATE_ROBOT_GAME");
/* 22 */
Profiler.ID_ROBOT_DO_MOVE = Profiler.getNewId("ID_ROBOT_DO_MOVE");
/* 23 */
Profiler.ID_ROBOT_CHECKWINNER = Profiler.getNewId("ID_ROBOT_CHECKWINNER");
/* 24 */
Profiler.ID_ROBOT_CLOSE_GAME = Profiler.getNewId("ID_ROBOT_CLOSE_GAME");
/* LogicXO */
/* 25 */
Profiler.LOGIC_XO_FIND_WIN_LINE = Profiler.getNewId("LOGIC_XO_FIND_WIN_LINE");
/* ActionsRepeatGame */
/* 26 */
Profiler.ID_REPEATE_GAME = Profiler.getNewId("ID_REPEATE_GAME");
/* 27 */
Profiler.ID_GENERATE_LINES = Profiler.getNewId("ID_GENERATE_LINES");
/* Rating */
/* 28 */
Profiler.ID_RATING_UPDATE = Profiler.getNewId("ID_RATING_UPDATE");
/* 29 */
Profiler.ID_ROBOT_THINKING = Profiler.getNewId("ID_ROBOT_THINKING");
/* 30 */
Profiler.ID_CHAT_SEND_BEFORE_ID = Profiler.getNewId("ID_CHAT_SEND_BEFORE_ID");
/* 31 */
Profiler.ID_RATING_UPDATE_STEP_1 = Profiler.getNewId("ID_RATING_UPDATE_STEP_1");
/* 32 */
Profiler.ID_RATING_UPDATE_STEP_2 = Profiler.getNewId("ID_RATING_UPDATE_STEP_2");
/* 33 */
Profiler.ID_RATING_UPDATE_STEP_3 = Profiler.getNewId("ID_RATING_UPDATE_STEP_3");
/* 34 */
Profiler.ID_RATING_UPDATE_STEP_4 = Profiler.getNewId("ID_RATING_UPDATE_STEP_4");
/* 35 */
Profiler.ID_WALLPOST_SUM = Profiler.getNewId('ID_WALLPOST_SUM');
Profiler.ID_WALLPOST_RECEIVE_DATA = Profiler.getNewId('ID_WALLPOST_RECEIVE_DATA');
Profiler.ID_WALLPOST_WRITE_FILE = Profiler.getNewId('ID_WALLPOST_WRITE_FILE');
Profiler.ID_WALLPOST_SEND_TO_VK_SERVER = Profiler.getNewId('ID_WALLPOST_SEND_TO_VK_SERVER');